
package coursemanagementsystem;

import java.awt.GridLayout;
import javax.swing.JFrame;
import java.util.*;
import java.io.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class CourseUpdateDeleteForm extends javax.swing.JFrame {
 JFrame jFrame=new JFrame("Sign Up Form");
    
 String section;
 
  String subject;
 
    JTextField jTextFiledSubjectName=new JTextField();
    
    JTextField jTextFiledSubjectTitle=new JTextField();
    
    JTextField jTextFiledSubjectSection=new JTextField();
    
    JTextField jTextFiledSubjectFaculty=new JTextField();
    
    JTextField jTextFiledSubjectStudent=new JTextField();
   
    JLabel jLabelSubjectName=new JLabel("Course Name");
    
    JLabel jLabelSubjectTitle=new JLabel("Course Title");
    
    JLabel jLabelSubjectSection=new JLabel("Section");
    
    JLabel jLabelSubjectFaculty=new JLabel("Faculty");
    
    JLabel jLabelSubjectStudent=new JLabel("Student");
    
    JLabel jLabel=new JLabel();
    
   
//    JButton jButtonUpdate=new JButton("Update Data");
    
  //  JButton jButtonDelete=new JButton("Delete Data");
    
    FileWriter fileWriter;
    CourseInformationSampleClassAll courseInformationSampleClassAll=new CourseInformationSampleClassAll();
    /**
     * Creates new form CourseUpdateDeleteForm
     */
    public CourseUpdateDeleteForm() {
      // JOptionPane.showMessageDialog(null, "If you want to show data you have to must enter your course name and section");
        initComponents();
   JOptionPane.showMessageDialog(null, "If you want to show data you have to must enter your course name and section");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelCourseName = new javax.swing.JLabel();
        jLabelCourseSection = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFiledCourseSection = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextFiledCourseName = new javax.swing.JTextPane();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonShowData = new javax.swing.JButton();
        jLabelCourseTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextFiledCourseTitle = new javax.swing.JTextPane();
        jLabelCourseFaculty = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextFiledCourseFaculty = new javax.swing.JTextPane();
        jLabelCourseStudent = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextFiledCourseStudent = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update and Delete");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("     -");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addGap(557, 557, 557))
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabelCourseName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCourseName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCourseName.setText("Course Name: ");

        jLabelCourseSection.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCourseSection.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCourseSection.setText("Section: ");

        jScrollPane1.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane1.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane1.setViewportView(jTextFiledCourseSection);

        jScrollPane2.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane2.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane2.setViewportView(jTextFiledCourseName);

        jButtonUpdate.setBackground(new java.awt.Color(102, 255, 102));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 51, 0));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseClicked(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(102, 255, 102));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 51, 0));
        jButtonDelete.setText("Delete");
        jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseClicked(evt);
            }
        });

        jButtonShowData.setBackground(new java.awt.Color(51, 255, 51));
        jButtonShowData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonShowData.setForeground(new java.awt.Color(255, 51, 51));
        jButtonShowData.setText("Show Data");
        jButtonShowData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonShowDataMouseClicked(evt);
            }
        });

        jLabelCourseTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCourseTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCourseTitle.setText("Title:");

        jScrollPane3.setBackground(new java.awt.Color(51, 255, 51));
        jScrollPane3.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFiledCourseTitle.setBackground(new java.awt.Color(102, 255, 102));
        jTextFiledCourseTitle.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane3.setViewportView(jTextFiledCourseTitle);

        jLabelCourseFaculty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCourseFaculty.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCourseFaculty.setText("Faculty:");

        jScrollPane5.setBackground(new java.awt.Color(51, 255, 51));
        jScrollPane5.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFiledCourseFaculty.setBackground(new java.awt.Color(102, 255, 102));
        jTextFiledCourseFaculty.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane5.setViewportView(jTextFiledCourseFaculty);

        jLabelCourseStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCourseStudent.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCourseStudent.setText("Student:");

        jScrollPane4.setBackground(new java.awt.Color(51, 255, 51));
        jScrollPane4.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFiledCourseStudent.setBackground(new java.awt.Color(102, 255, 102));
        jTextFiledCourseStudent.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane4.setViewportView(jTextFiledCourseStudent);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelCourseName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonUpdate)
                                    .addComponent(jLabelCourseSection))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonShowData)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonDelete)
                                        .addGap(9, 9, 9)))))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelCourseStudent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelCourseFaculty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelCourseTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCourseName)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCourseSection)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCourseTitle)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCourseFaculty)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCourseStudent))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonShowData)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButtonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseClicked
        // TODO add your handling code here:
 String section=jLabelCourseSection.getText().toString().trim()+" : "+jTextFiledCourseSection.getText().toString().trim();
 subject=jLabelCourseName.getText().toString().trim()+" : "+jTextFiledCourseName.getText().toString().trim();
 String subjectTitle=jLabelCourseTitle.getText().toString().trim()+" : "+jTextFiledCourseTitle.getText().toString().trim();
 String subjectFaculty=jLabelCourseFaculty.getText().toString().trim()+" : "+jTextFiledCourseFaculty.getText().toString().trim();
 String subjectStudent=jLabelCourseStudent.getText().toString().trim()+" : "+jTextFiledCourseStudent.getText().toString().trim();        
  
 UpdateDeleteCompleteSampleClass updateDeleteCompleteSampleClass=new UpdateDeleteCompleteSampleClass(subject,section,subjectTitle,subjectFaculty,subjectStudent);      
        
 int checkvalue=updateDeleteCompleteSampleClass.UpdateFile();
 
 if(checkvalue==1){
     
     JOptionPane.showMessageDialog(null, "The data is updated succesfully");
 
 }else{
 
     JOptionPane.showMessageDialog(null, "The data is not updated succesfully");
 
 }
 
    }//GEN-LAST:event_jButtonUpdateMouseClicked

    private void jButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseClicked
        // TODO add your handling code here:
        
          section=jLabelCourseSection.getText().toString().trim()+" : "+jTextFiledCourseSection.getText().toString().trim();
         subject=jLabelCourseName.getText().toString().trim()+" : "+jTextFiledCourseName.getText().toString().trim();
         String subjectTitle=jLabelCourseTitle.getText().toString().trim()+" : "+jTextFiledCourseTitle.getText().toString().trim();
 String subjectFaculty=jLabelCourseFaculty.getText().toString().trim()+" : "+jTextFiledCourseFaculty.getText().toString().trim();
 String subjectStudent=jLabelCourseStudent.getText().toString().trim()+" : "+jTextFiledCourseStudent.getText().toString().trim();        
                           
 UpdateDeleteCompleteSampleClass updateDeleteCompleteSampleClass=new UpdateDeleteCompleteSampleClass(subject,section,subjectTitle,subjectFaculty,subjectStudent);      
        
 int checkvalue=updateDeleteCompleteSampleClass.Delete();
 
 if(checkvalue==1){
     
     JOptionPane.showMessageDialog(null, "The data is deleted succesfully");
 
 }else{
 
     JOptionPane.showMessageDialog(null, "The data is not deleted succesfully");
 
 }
         
         
    }//GEN-LAST:event_jButtonDeleteMouseClicked

    private void jButtonShowDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonShowDataMouseClicked
        // TODO add your handling code here:
//jButtonShowData
        File file=new File("CourseDetailsInformation.txt");
//JOptionPane.showMessageDialog(null, "I am into the showbutton");
        try{

             section=jLabelCourseSection.getText().toString().trim()+" : "+jTextFiledCourseSection.getText().toString().trim();
         subject=jLabelCourseName.getText().toString().trim()+" : "+jTextFiledCourseName.getText().toString().trim();
            
            Scanner scanner=new Scanner(file);

            LinkedList <CourseInformationSampleClassAll> arrayList=new LinkedList<CourseInformationSampleClassAll>();

            GridLayout gridLayout=new GridLayout();

            gridLayout.setColumns(1);
            gridLayout.setRows(6);

            jFrame.setLayout(gridLayout);

            while(scanner.hasNext()){

                String course=scanner.nextLine();

                //   jFrame.add(jLabelSubjectName);
               

                //            JOptionPane.showMessageDialog(null, ""+course);
                //  arrayList.add(course+"\n");
                String title=scanner.nextLine();

                // jFrame.add(jLabelSubjectTitle);
               
                //          JOptionPane.showMessageDialog(null, ""+title);
                //arrayList.add(title+"\n");
                String section1=scanner.nextLine();

                // jFrame.add(jLabelSubjectSection);
                
                //        JOptionPane.showMessageDialog(null, ""+section);
                //arrayList.add(section+"\n");
                String faculty=scanner.nextLine();

                //jFrame.add(jLabelSubjectFaculty);
                
                //      JOptionPane.showMessageDialog(null, ""+faculty);
                //arrayList.add(faculty+"\n");
                String student=scanner.nextLine();

                //jFrame.add(jLabelSubjectStudent);
                
                //    JOptionPane.showMessageDialog(null, ""+student);
                //arrayList.add(student+"\n");

                String line1=scanner.nextLine();
                //JOptionPane.showMessageDialog(null, ""+line1);

                // String line1=scanner.nextLine();
                String line2=scanner.nextLine();

   if(subject.equalsIgnoreCase(course) && section.equalsIgnoreCase(section1)){
                jTextFiledSubjectName.setText(course);
                jFrame.add(jTextFiledSubjectName);
                jTextFiledSubjectName.setEditable(false);
                courseInformationSampleClassAll.setCourseName(course);     
                jTextFiledSubjectTitle.setText(title);
                jFrame.add(jTextFiledSubjectTitle);

                courseInformationSampleClassAll.setCourseTitle(title);     
   jTextFiledSubjectSection.setText(section1);
                jFrame.add(jTextFiledSubjectSection);
jTextFiledSubjectSection.setEditable(false);
                courseInformationSampleClassAll.setCourseSection(section1);  
   
   jTextFiledSubjectFaculty.setText(faculty);
                jFrame.add(jTextFiledSubjectFaculty);
jTextFiledSubjectFaculty.setEditable(false);
                courseInformationSampleClassAll.setCourseFaculty(faculty);
   
                jTextFiledSubjectStudent.setText(student);
                jFrame.add(jTextFiledSubjectStudent);
jTextFiledSubjectStudent.setEditable(false);
                courseInformationSampleClassAll.setCourseStudent(student);
   
   jFrame.setSize(600, 600);
                jFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                jFrame.setVisible(true);
   
   }else{
  // JOptionPane.showMessageDialog(null, "I am here");    
   }
                            
                CourseInformationSampleClassAll courseInformationSampleClassAll=new CourseInformationSampleClassAll(course, title, faculty, section, student);

                arrayList.add(courseInformationSampleClassAll);

                //jFrame.add(jButtonUpdate);
                //jFrame.add(jLabel);
                //jFrame.add(jButtonDelete);
              
                //JOptionPane.showMessageDialog(null, courseInformationSampleClassAll.getCourseName()+"\n"+courseInformationSampleClassAll.getCourseTitle()+"\n"+courseInformationSampleClassAll.getCourseSection()+"\n"+courseInformationSampleClassAll.getCourseFaculty()+"\n"+courseInformationSampleClassAll.getCourseStudent()+"\n");

                // JOptionPane.showMessageDialog(null, arrayList);
            }

            //  JOptionPane.showMessageDialog(null, courseInformationSampleClassAll.getCourseName()+"\n"+courseInformationSampleClassAll.getCourseTitle()+"\n"+courseInformationSampleClassAll.getCourseSection()+"\n"+courseInformationSampleClassAll.getCourseFaculty()+"\n"+courseInformationSampleClassAll.getCourseStudent()+"\n");

        }catch(Exception exception){

            //JOptionPane.showMessageDialog(null, exception);

        }

    }//GEN-LAST:event_jButtonShowDataMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseUpdateDeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseUpdateDeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseUpdateDeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseUpdateDeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CourseUpdateDeleteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonShowData;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCourseFaculty;
    private javax.swing.JLabel jLabelCourseName;
    private javax.swing.JLabel jLabelCourseSection;
    private javax.swing.JLabel jLabelCourseStudent;
    private javax.swing.JLabel jLabelCourseTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextFiledCourseFaculty;
    private javax.swing.JTextPane jTextFiledCourseName;
    private javax.swing.JTextPane jTextFiledCourseSection;
    private javax.swing.JTextPane jTextFiledCourseStudent;
    private javax.swing.JTextPane jTextFiledCourseTitle;
    // End of variables declaration//GEN-END:variables
}
